### ISSUE TITLE
Map properties in CSV medical files to SNOMED IDs

### ISSUE THREAD

**Issue by DaniFdezAlvarez** [alijaalejandro/SNOMED-Analytics#13]

**Comment by DaniFdezAlvarez** [comment]
I selected all the values from the file of acute_inflamations and mainly disorders from the file of cancer cervical. Both archives are csv, the next JSON maps index of columns in the TSV to SNOMED concepts. The indexes that appear correspond to the values that I am using. Ask me if you need the file or you want to change the selected set.

{
	"acute": {
		"0" : {
			"sctid" : "386725007",
			"type" : "observable entity",
			"lang" : {
				"es" : "Temperatura corporal",
				"en" : "Body temperature"
			}	
		},
		"1" : {
			"sctid" : "422587007",
			"type" : "finding",
			"lang" : {
				"es" : "Náuseas",
				"en" : "Nausea"
			}	
		},
		"2" : {
			"sctid" : "279039007",
			"type" : "finding",
			"lang" : {
				"es" : "Lumbalgia",
				"en" : "Low back pain"
			}	
		},
		"3" : {
			"sctid" : "75088002",
			"type" : "finding",
			"lang" : {
				"es" : "Necesidad imperiosa de urinar",
				"en" : "Urinary precipitancy"
			}	
		},
		"4" : {
			"sctid" : "49650001",
			"type" : "finding",
			"lang" : {
				"es" : "Dosuria",
				"en" : "Dysuria"
			}	
		},
		"5" : {
			"sctid" : "6561007",
			"type" : "finding",
			"lang" : {
				"es" : "Dolor de uretra",
				"en" : "Pain in urethra"
			}	
		},
		"6" : {
			"sctid" : "38822007",
			"type" : "disorder",
			"lang" : {
				"es" : "Cistitis",
				"en" : "Cystitis"
			}	
		},
		"7" : {
			"sctid" : "45816000",
			"type" : "disorder",
			"lang" : {
				"es" : "Pielonefritis",
				"en" : "Pyelonephritis"
			}	
		}
	},
	"cervical_cancer" : {
		"0" : {
			"sctid" : "397669002",
			"type" : "qualifier value",
			"lang" : {
				"es" : "Edad",
				"en" : "Age"
			}	
		},
		"4" : {
			"sctid" : "77176002",
			"type" : "finding",
			"lang" : {
				"es" : "Fumador",
				"en" : "Smoker"
			}	
		},
		"17" : {
			"sctid" : "76272004",
			"type" : "disorder",
			"lang" : {
				"es" : "Sífilis",
				"en" : "Syphilis"
			}	
		},
		"18" : {
			"sctid" : "198130006",
			"type" : "disorder",
			"lang" : {
				"es" : "Enfermedad inflamatoria pélvica en la mujer",
				"en" : "Female pelvic inflammatory disease"
			}	
		},
		"19" : {
			"sctid" : "33839006",
			"type" : "disorder",
			"lang" : {
				"es" : "Herpes genital",
				"en" : "Genital Herpes"
			}	
		},
		"21" : {
			"sctid" : "397669002",
			"type" : "disorder",
			"lang" : {
				"es" : "Síndrome de inmunodeficiencia adquirido",
				"en" : "Acquired immune deficiency syndrome"
			}	
		},
		"23" : {
			"sctid" : "66071002",
			"type" : "disorder",
			"lang" : {
				"es" : "Hepatitis viral tipo B",
				"en" : "Viral hepatitis type B"
			}	
		}
	}
}

**Comment by alijaalejandro** [comment]
Hola Dani. Se que estás haciendo muchos avances. Perdóname pero estoy a
tope literalmente. La semana que viene lo reviso. Tu no pares, seguir
adelante.
Álex
