### ISSUE TITLE
JSON model to store patients info

### ISSUE THREAD

**Issue by DaniFdezAlvarez** [alijaalejandro/SNOMED-Analytics#14]

**Comment by DaniFdezAlvarez** [comment]
@herminiogg , proposal of JSON for each patient:
{
  "age": 40,
  "disorders": [
    "38822007"
  ],
  "findings": [
    "75088002",
    "49650001",
    "6561007"
  ],
  "follow": true,
  "id": "3759218440P",
  "name": "Thomas",
  "qualifiers": {
    "386725007": "35.9"
  },
  "surname": "Tauscher"
}

**Comment by herminiogg** [comment]
Imagino que disorders se refiere a enfermedades que están padeciendo, findings a enfermedades que se han encontrado (en cualquier intervalo de tiempo) y lo que no entiendo es lo de qualifiers. ¿Es esto así?

**Comment by DaniFdezAlvarez** [comment]
Sí, o casí sí. Las categoriás esas son las que vienen asociadas a cada concepto en SNOMED . Lo que yo entiendo al menos es que disorders son efectivamente enfermedades ya diagnosticadas que se están padeciendo. Findings (hallazgos en la versión española) lo entiendo como aquello que el médico te descubre o anota sobre ti cuando vas a la consultas, que puede ser una enfermedad u otra cosa. Por ejemplo, hablando de memoria, catarro puede ser un finding, pero también dolor de cabeza o náuseas, que son más bien síntomas. Incluso ser fumador se trata como finding. En un modelo de datos completo, entiendo que los findings deberían ir necesariamente asociados a la fecha en la que se anotan, pero no creo que nos haga falta para la demo.

Sobre los qualifiers: son sucesos observables que no se califican con booleanos. Tanto finding como disorder se califican con "se tiene o no se tiene", entonces basta con poner el identificador en la lista para decir se tiene y no ponerlo para lo contrario. En el ejemplo ese, el qualifier que hay es fiebre, que le tienes que asociar un valor en grados para dar la información completa. Aunque fiebre quizá tambiñen pueda ser un dato prescindible para la demo.

"Edad" en realidad tambiñen tiene su identificador en SNOMED y entra en qualifiers, pero prescindí de él.

**Comment by herminiogg** [comment]
Igual si necesitamos que se tenga en cuenta la fecha según esta diseñada la interfaz ahora. Parece lógico que un finding esté circunscrito a un momento temporal y puede ser una manera fácil de ordenar la tabla final.

**Comment by DaniFdezAlvarez** [comment]
Para adentro que va entonces. Meteré fechas aleatorias en findings. Quedaría algo como esto:
{
"age": 40,
"disorders": [
"38822007"
],
"findings": {
"10/10/2017": [
"75088002",
"49650001"
],
"15/10/2017" : [
"6561007"
]
},
"follow": true,
"id": "3759218440P",
"name": "Thomas",
"qualifiers": {
"386725007": "35.9"
},
"surname": "Tauscher"
}
